ci:
  autofix_prs: false

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/lucianopaz/head_of_apache
    rev: "0.0.3"
    hooks:
      - id: head_of_apache
        args:
          - --author=The PyMC Labs Developers
          - --exclude=docs/
          - --exclude=scripts/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: check-yaml
      - id: check-added-large-files
        exclude: &exclude_pattern 'iv_weak_instruments.ipynb'
        args: ["--maxkb=1500"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      # Run the linter
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        # needed to make excludes in pyproject.toml work
        # see here https://github.com/econchick/interrogate/issues/60#issuecomment-735436566
        pass_filenames: false
  - repo: local
    hooks:
      - id: convert-notebooks
        name: Convert Notebooks to Markdown
        entry: python ./.codespell/notebook_to_markdown.py
        language: python
        pass_filenames: false
        always_run: false
        additional_dependencies: ["nbconvert", "nbformat"]
        args: ["--tempdir", "tmp_markdown"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [
            "-S",
            "*.csv",
            "-S",
            "pyproject.toml",
            "-S",
            "*.svg",
            "-S",
            "*.ipynb",
            "--ignore-words=./.codespell/codespell-whitelist.txt",
          ]
        additional_dependencies:
          # Support pyproject.toml configuration
          - tomli
  - repo: local
    hooks:
      - id: remove-temp-directory-notebooks
        name: Remove temporary directory for codespell
        entry: bash -c 'rm -rf tmp_markdown && exit 0'
        language: system
        always_run: true
        pass_filenames: false
