name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

defaults:
  run:
    # Ensure activation for micromamba
    shell: bash -leo pipefail {0} {0}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run lint
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Rename lockfile
        run: |
          mv conda/conda-lock-${{ matrix.python-version }}.yaml conda/conda-lock.yml
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 1.5.5-0
          environment-file: conda/conda-lock.yml
          environment-name: causalpy-test-${{ matrix.python-version }}
          cache-environment: true
          create-args: >-
            --category main
            --category dev
      - name: Run doctests
        run: |
          pip install -e .[test]
          pytest --doctest-modules causalpy/
      - name: Run tests
        run: |
          pip install -e .[test]
          pytest --cov-report=xml --no-cov-on-fail
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # use token for more robust uploads
          name: ${{ matrix.python-version }}
          fail_ci_if_error: false
