name: Perform pre-commit checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: ${{ matrix.os }} pre-commit
    steps:
    # Initialization
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11


    # Basic install
    - name: Install pre-commit
      run: python -m pip install pre-commit
    - name: List pip package versions
      run: python -m pip freeze --local

    # Run pre-commit
    - name: RUN PRE-COMMIT
      run: pre-commit run --show-diff-on-failure --color=always --all-files

    # Upload logs
    - name: Upload pre-commit log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pre-commit-log-${{ matrix.os }}
        path: /home/runner/.cache/pre-commit/pre-commit.log
